###
GET http://localhost/dossier_projet_formation/restaurant_projet-front/mealsRead.php HTTP/1.1

###
POST http://localhost/dossier_projet_formation/restaurant_projet-front/mealsCreate.php HTTP/1.1

{
    "meals_title": "test",
    "meals_description": "test",
    "meals_price": 12
}